language: go

os:
  - linux
#  - osx

go:
  - 1.8.3

services:
  - docker
env:
  global:
#    - CONTROLLER_IMAGE=${CONTROLLER_IMAGE_NAME}:${TRAVIS_TAG:-build-$TRAVIS_BUILD_ID}
    - CGO_ENABLED=0

before_install:
  - set -e

install:
  - |-
    curl -Ls https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/$(go env GOOS)/$(go env GOARCH)/kubectl |\
        install /dev/stdin ${GOPATH:?}/bin/kubectl
  - |-
    curl -Ls https://github.com/ksonnet/kubecfg/releases/download/v0.4.0/kubecfg-$(go env GOOS)-$(go env GOARCH) | \
        install /dev/stdin ${GOPATH:?}/bin/kubecfg
  - git clone --depth=1 https://github.com/sstephenson/bats.git bats
  - export PATH=$PATH:$GOPATH/bin:$PWD/bats/bin

script:
  - |
    if [ "$TRAVIS_OS_NAME" = linux ]; then
      make integration-tests
    fi

after_success:
  - true
